In [24]:
# import numpy library

import numpy as np

In [25]:
# make an array

a = np.array( [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [26]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
# access elements, using indices, similar to a list

a[0,0]

1

In [28]:
a[2,1]

8

In [29]:
a[1]

array([4, 5, 6])

In [30]:
a[:,1]

array([2, 5, 8])

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
# array operations
a * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [36]:
a.mean()

5.0

In [40]:
a.sum()

45

In [41]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])